xml name: you's blog
title: you's blog
version: 3.6.0

description: >- 
  An archive of my thoughts.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.yougao.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  You-Gao

author: You Gao
website: https://www.yougao.dev/
xml: https://blog.yougao.dev/feed.xml/
email: mail@yougao.dev

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true

collections:
  books:
    output: true
    permalink: /books/:title/
  fun:
    output: true
    permalink: /fun/:title/
  life:
    output: true
    permalink: /life/:title/
  work:
    output: true
    permalink: /work/:title/
  photos:
    output: true
    permalink: /photos/:title/

image:
  path: /assets/logo.png
  height: 192
  width: 192
