name: you's blog
title: false

description: >- # this means to ignore newlines until "baseurl:"
  An archive of my thoughts on life.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.yougao.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  You-Gao

author: You Gao
website: https://www.yougao.dev/
email: mail@yougao.dev

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  books:
    output: true
    permalink: /books/:title/
  games:
    output: true
    permalink: /games/:title/
  life:
    output: true
    permalink: /life/:title/
  work:
    output: true
    permalink: /work/:title/

image:
  path: /assets/logo.png
  height: 192
  width: 192