name: Henry's Blog
title: You Gao

description: >- # this means to ignore newlines until "baseurl:"
  An archive of my thoughts about life and probably everything else.

baseurl: "/Blog" # the subpath of your site, e.g. /blog
url: "https://yougao.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  You-Gao
